[env:esp32-s3-r8n16]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

monitor_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -Wno-error=return-type

lib_deps =
    adafruit/Adafruit NeoPixel
    thomasfredericks/Bounce2
    olikraus/U8g2
    spirik/GEM@^1.8.1
    fortyseveneffects/MIDI Library@^5.0.2
    adafruit/Adafruit GFX Library @ ^1.11
    adafruit/Adafruit BusIO @ ^1.16